apiVersion: v1
kind: ResourceQuota
metadata:
  name: nsprq
  namespace: nagprd
spec:
  hard:
   requests.cpu: '0.5'
   requests.memory: 1Gi  
   limits.cpu: '1'
   limits.memory: 2Gi
   configmaps: "10"
   persistentvolumeclaims: "4"
   pods: "4"
   replicationcontrollers: "20"
   secrets: "10"
   services: "10"
   services.loadbalancers: "2"



